name: rust-compiler
on:
  push:
    branches: ["master", "ci/add-rust-test"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/cargo@v1
        with:
          command: test