name: rust-compiler
on:
  push:
    branches: ["master", "ci/add-rust-test"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Install LLVM 15 for inkwell and llvm-sys
      - run: apt update
      - run: apt install -y llvm-15
      - run: echo "export LLVM_SYS_150_PREFIX="/lib/llvm-15"" > ~/.bashrc
      - run: source ~/.bashrc
      - run: echo $LLVM_SYS_150_PREFIX